const foodItemData = [
    {
        id: 1,
        name: 'Normal Bhat',
        desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium',
        rating: 4,
        price: 20,
        img: 'image/normal-rice.jpg',
        category: 'rice',
        isWishList: false,
    },
    {
        id: 2,
        name: 'Deshi Dal',
        desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium',
        rating: 4,
        price: 10,
        img: 'image/dal.jpg',
        category: 'dal',
        isWishList: false,
    },
    {
        id: 3,
        name: 'Deshi Murgi',
        desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium',
        rating: 3,
        price: 50,
        img: 'image/chicken.jpg',
        category: 'meat',
        isWishList: false,
    },
    {
        id: 4,
        name: 'Dim',
        desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium',
        rating: 5,
        price: 25,
        img: 'image/egg.jpg',
        category: 'egg',
        isWishList: false,
    },
    {
        id: 5,
        name: 'Gorur Magso',
        desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi, accusantium',
        rating: 5,
        price: 80,
        img: 'image/cow-meat.jpg',
        category: 'meat',
        isWishList: false,
    },
]